#!/bin/sh

# Last Update : %s
SOURCE_CERT=%s
DEST_CERT=%s
SOURCE_KEY=%s
DEST_KEY=%s
TOMCAT_USER=%s
TOMCAT_GRP=%s

cp $SOURCE_CERT $DEST_CERT
cp $SOURCE_KEY $DEST_KEY

chown $TOMCAT_USER:$TOMCAT_GRP $DEST_CERT
chown $TOMCAT_USER:$TOMCAT_GRP $DEST_KEY
