#! /usr/bin/perl

use strict;
use warnings;

use XML::Simple;
use Data::Dumper;

my $str=shift;
my $xml=shift;
my $tag=shift;

my $rules = XMLin($xml);

my $selected_rules=$rules->{$tag};

$selected_rules = [ $selected_rules ] unless(ref $selected_rules eq 'ARRAY');

foreach my $rule (@{$selected_rules}){
    if( $str =~ /$rule->{match}/ ){
        print eval('"'.$rule->{result}.'"');
        exit 0;
    }
}

exit 0;
